### ISSUE TITLE
Node Red on port 80

### ISSUE THREAD

**Issue by twocolors** [NRCHKB/node-red-contrib-homekit-docker#5]
Support run node red on port 80

**Comment by Shaquu** [comment]
I think it is already supported. Just pass process.env.PORT value to container.

**Comment by twocolors** [comment]
```24 Aug 10:22:37 - [error] Uncaught Exception:
24 Aug 10:22:37 - [error] Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1498:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-contrib-homekit-docker@1.1.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-contrib-homekit-docker@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2020-08-24T07_22_37_262Z-debug.log
Starting node-red

> node-red-contrib-homekit-docker@1.1.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"```

cap_net_bind_service=+ep for node ?

**Comment by oliverrahner** [comment]
The reason for this is almost certainly that you try to do this as non-root. Only root is allowed to bind to ports <1024.

**Comment by oliverrahner** [comment]
The problem here is that the container runs node-red as uid 1000. Only root is allowed to bind to ports <= 1024.

**Comment by twocolors** [comment]
@Shaquu plz fix this

**Comment by Shaquu** [comment]
@twocolors got it, let me see

**Comment by twocolors** [comment]
thx, all work

**Comment by Shaquu** [comment]
@twocolors could you please verify it on newest docker image?
